config/routes.rb
Rails.application.routes.draw do 
	root 'pages#home'
	get 'about' => 'pages#about'
	get 'contact-us' => 'pages#contact-us'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
        </ul>
      </div>
    </nav>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.</p>
    </div>
</div>

app/views/pages/contact-us.html.erb
<h1>Contact Us</h1>
<p>You can reach me at arueda@gitlab.com</p>

app/views/pages/home.html.erb
<div class="jumbotron jumbotron-home">
    <div class="container">
        <h1>Welcome to Amanda's website!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Family</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Fun</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Future</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>